import { Inter } from "next/font/google";
import Provider from "../../context/Provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          {children}
          <footer className="border-t text-center text-gray-500 p-8 mt-16">
            &copy; {new Date().getFullYear()} Gichuki All rights reserved
          </footer>
        </body>
      </Provider>
    </html>
  );
}
